### ISSUE TITLE
Define types of banner notifications

### ISSUE THREAD

**Issue by edwardbarraza** [NASA-PDS/pds-wds#6]
We need to define the notification categories for banners
We also need to discern between node notifications and node announcements

**Comment by anilnatha** [comment]
## Banner Notification Details

### What This Is

To warrant the need of posting a banner notification, the information should meet multiple conditions of the criteria listed below. This is to ensure users do not become numb to overuse of banner notifications.

 1. Affects a large percentage of the user base.
 2. Has a higher significance.
 3. Requires a call to action
 4. Is time sensitive.

### What this isn't

 1. Individual user focused messaging.  Messages that target a specific user should use other methods, like targeted emails, account notifications, badges, etc.

### Use Cases

#### Low Priority 
 1. Successful Website Updates
 2. Newly Released datasets

#### Medium Priority
 1. Distant-future time sensitive information. (e.g. future website downtime)
 2. Distant-future time sensitive call-to-action. (e.g. survey expiration, sign-up deadline, etc.)

#### High Priority
 1. Imminent time-sensitive call-to-action. 
 2. Website/System impending downtime due to regular maintenance
 3. Website/System failure due
 4. Other emergencies

## Styling

Based on the above criteria, there are four categories of banner messages we should employ:

 1. Informational (Blue)
 2. Success (Green)
 3. Warning (Yellow/Orange)
 4. Danger/Error (Red)

_It's important to note that these categories also follow typical feedback coloring patterns so that it is easier for users to understand the importance of the information contained in the banner using color association._

---
**_This isn't final, I wrote this to get the conversation started._**

**Comment by jordanpadams** [comment]
closing new solution with HDS coming soon...
